// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbtHK7D7z8sPAOkttbz-y9kb4lJtorKk',
    appId: '1:874159834919:web:7cefeef7fc447203f40b02',
    messagingSenderId: '874159834919',
    projectId: 'flash-chat-28bdd',
    authDomain: 'flash-chat-28bdd.firebaseapp.com',
    storageBucket: 'flash-chat-28bdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAt-5ogWBsdNoUQ8ptTAGUIddt9JUKf4',
    appId: '1:874159834919:android:87b5d2727efdc288f40b02',
    messagingSenderId: '874159834919',
    projectId: 'flash-chat-28bdd',
    storageBucket: 'flash-chat-28bdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7UN4v8yxekl89oLzQdRmK6cOuapbXtN4',
    appId: '1:874159834919:ios:d46b8d2e26ed2758f40b02',
    messagingSenderId: '874159834919',
    projectId: 'flash-chat-28bdd',
    storageBucket: 'flash-chat-28bdd.appspot.com',
    iosBundleId: 'com.example.flashChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7UN4v8yxekl89oLzQdRmK6cOuapbXtN4',
    appId: '1:874159834919:ios:d46b8d2e26ed2758f40b02',
    messagingSenderId: '874159834919',
    projectId: 'flash-chat-28bdd',
    storageBucket: 'flash-chat-28bdd.appspot.com',
    iosBundleId: 'com.example.flashChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvbtHK7D7z8sPAOkttbz-y9kb4lJtorKk',
    appId: '1:874159834919:web:9907d07e77fb12fef40b02',
    messagingSenderId: '874159834919',
    projectId: 'flash-chat-28bdd',
    authDomain: 'flash-chat-28bdd.firebaseapp.com',
    storageBucket: 'flash-chat-28bdd.appspot.com',
  );
}
